### ISSUE TITLE
Allow to load another file after a frist file has been loaded

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort-workbench#108]
Offer a UI to load another file without the need to close and reopen the workbench.

**Comment by sschuberth** [comment]
I just discovered "Load new file" under "ORT Result File" in the "Summary" 😆 So the feature is there there, but we should probably improve the UI for it 😉

**Comment by mnonnenmacher** [comment]
Yes, I plan to add a new UI for that that also allows having multiple files open.
