### ISSUE TITLE
Allow drag & drop of files to load onto the initial screen

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort-workbench#65]
The title says it all 😀

**Comment by sschuberth** [comment]
Looks like this is way more complicated that I thought: https://github.com/JetBrains/compose-jb/issues/222

**Comment by mnonnenmacher** [comment]
Supported since https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.4.0, introduced in https://github.com/JetBrains/compose-multiplatform-core/pull/391/files#diff-a7b66aa6b5919ed2b164bcda7341904749f6b15081f7ea109d89e8e82e47ba64.

**Comment by sschuberth** [comment]
FYI, I've started to work on this in the [external-drag-and-drop](https://github.com/oss-review-toolkit/ort-workbench/tree/external-drag-and-drop) branch, but I need help from @mnonnenmacher to continue.
